[program:artisan-migrate]
command=/bin/bash /var/www/html/docker/php/wait-and-migrate.sh
autostart=true
startretries=1
autorestart=false
priority=3
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
