[program:default]
process_name=%(program_name)s_%(process_num)02d
command=php -dxdebug.mode=off /var/www/html/artisan queue:work redis --queue=default --sleep=1 --tries=3 --max-time=3600 --max-jobs=10000
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=1000
numprocs=1
redirect_stderr=true
stdout_logfile=/var/www/html/storage/logs/queue-worker.log
