[program:frankenphp]
command=/bin/bash -c "cd /var/www/html/ && php artisan octane:frankenphp --workers=${OCTANE_WORKERS:-4} --caddyfile=./docker/Caddyfile"
priority=2
autostart=true
autorestart=true
startretries=30
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
